name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3  # Update to v3

      # Get the current date (new method)
      - name: Get Date
        id: get-date
        run: echo "DATE=$(date -u +'%Y%m%d')" >> $GITHUB_ENV  # Store in environment variable

      # Cache the Buildozer global directory
      - name: Cache Buildozer global directory
        uses: actions/cache@v3  # Update to v3
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      # Cache Buildozer directory using the date
      - uses: actions/cache@v3  # Update to v3
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ env.DATE }}-${{ hashFiles('buildozer.spec') }}

      # Build the project using Buildozer
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          buildozer_version: stable

      # Upload the artifacts (update to v3)
      - name: Upload artifacts
        uses: actions/upload-artifact@v3  # Update to v3
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
